### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by kangyang94** [huangmozhilv/promise12_vnet_pytorch#1]
Excuse me,could you tell me how to change the code to arrive your score? I only got the score as about 0.83

**Comment by kangyang94** [comment]
In "main.py" and "DataManager.py" ,I do not find where marked as "require customization"

**Comment by 12cheny** [comment]
@kangyang94  Have you applied this code? I couldn't run it.

**Comment by dPacc** [comment]
I'm getting the following error while running the `main.py` file. Could you please help me out

Traceback (most recent call last):
  File "main.py", line 82, in <module>
    train.main(params, args)
  File "/mnt/14A6B754A6B73558/folder_namei/V_Net/promise12_vnet_pytorch-master/train.py", line 295, in main
    dataManagerTrain.loadTrainingData()  # required
  File "/mnt/14A6B754A6B73558/folder_name/V_Net/promise12_vnet_pytorch-master/DataManager.py", line 67, in loadTrainingData
    self.loadImages()
  File "/mnt/14A6B754A6B73558/folder_name/V_Net/promise12_vnet_pytorch-master/DataManager.py", line 54, in loadImages
    self.meanIntensityTrain=m/len(self.sitkImages)
ZeroDivisionError: float division by zero

**Comment by huangmozhilv** [comment]
@dPacc I think the `len(self.sitkImages)` is 0. It seems the `self.loadImages()` failed.

**Comment by huangmozhilv** [comment]
@kangyang94 You can try to run the code first. If failed, it could be that the data path should be changed or some other codes requiring customized. You can find out why according to the errors information by running the code.
