### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by dPacc** [huangmozhilv/promise12_vnet_pytorch#2]
This is the error I get while running the `main.py` file. I have modified the files you mentioned.

Traceback (most recent call last):
  File "main.py", line 82, in <module>
    train.main(params, args)
  File "/mnt/14A6B754A6B73558/Spline.ai/V_Net/promise12_vnet_pytorch-master/train.py", line 295, in main
    dataManagerTrain.loadTrainingData()  # required
  File "/mnt/14A6B754A6B73558/Spline.ai/V_Net/promise12_vnet_pytorch-master/DataManager.py", line 67, in loadTrainingData
    self.loadImages()
  File "/mnt/14A6B754A6B73558/Spline.ai/V_Net/promise12_vnet_pytorch-master/DataManager.py", line 54, in loadImages
    self.meanIntensityTrain=m/len(self.sitkImages)
ZeroDivisionError: float division by zero

**Comment by jatinw21** [comment]
Seems like it couldn't find your training data. Is it in the right folders and right format? There should be 3 folders in the dataset folder that looks like this
- dataset
   - imagesTr
   - imagesTs
   - labelsTr

where each subfolder has images in form of .mhd and .raw files
